### ISSUE TITLE
dataset.get() cannot read tags with 4 elements

### ISSUE THREAD

**Issue by LudvigOlsen** [KitwareMedical/dicom-anonymizer#17]
In dicomfields, you have three tags with 4 indices:

E.g.
`(0x5000, 0x0000, 0xFF00, 0x0000), # Curve Data`

but `pydicom.dataset.get()` has the following interface:
`get(key: Union[int, Tuple[int, int], pydicom.tag.BaseTag], default: Optional[object] = 'None')`

so it doesn't recognize 4 ints as a tag. 

`TypeError: Dataset.get key must be a string or tag`

Are those three special tags common? :)

**Edit**:
I see that they are deleted without calling `get()`. But in `anonymize_data()` you call `.get()` on it and then print when it fails. So that happens for every file. So perhaps that part should not be run for tags with len > 2?

**Edit 2**:
I refined my idea for a solution in a PR https://github.com/KitwareMedical/dicom-anonymizer/pull/18

**Comment by laurennlam** [comment]
Thanks for sharing this issue.
Do you have a file you can share so that I can check this on my side ?

**Comment by LudvigOlsen** [comment]
Hi Laurenn, 

I don't have a file, I can share no. Does this not happen with the data you are testing with? 
I think pydicom might have a way to make a dummy image to test with.

**Comment by laurennlam** [comment]
I don't have any file with this kind of tag.
It seems that sometime, we handle this case :
```python
def delete(dataset, tag):
    """X - remove"""

    def range_callback(dataset, data_element):
        if data_element.tag.group & tag[2] == tag[0] and data_element.tag.element & tag[3] == tag[1]:
            delete_element(dataset, data_element)

    if len(tag) > 2:  # Tag ranges
        dataset.walk(range_callback)
```
When do you have the issue ? Can you describe more the context ?

**Comment by laurennlam** [comment]
I need to go deeper on Dicom tags to understand more this case.
Thanks!

**Comment by laurennlam** [comment]
After some reasearches, this kind of tag has been introduced in the library in order to manage [Repeating Groups](http://dicom.nema.org/dicom/2013/output/chtml/part05/sect_7.6.html).
Indeed, this case is not handled in the `anonymize_dataset ` function for private tags. I'll make a pull request for it. Also, it's a real issue if we change the default associated action to these tags. Today, there are deleted. The [delete ](https://github.com/KitwareMedical/dicom-anonymizer/blob/947066968b6013d351dd8d43a187317ea8064d77/dicomanonymizer/simpledicomanonymizer.py#L166) function manages the case with 4 tags but it's the only one.
That's why the `anonymize_dataset `  function needs to be updated in order to not adding this case in all actions methods.

So, to conclude, having 4 values in a tag is not a dicom convention but specific to this library.
Thanks for pointed it out.
